### ISSUE TITLE
need container image

### ISSUE THREAD

**Issue by jberkus** [projectatomic/commctl#24]
... so that we can use commctl on atomic

Just putting this here as a placeholder, I'll actually build the container later.

**Comment by mbarnes** [comment]
The `atomic` command already has Commissaire integration:

`atomic cluster ...` is equivalent to `commctl cluster ...`, and
`atomic rhost ...` is equivalent to `commctl host ...`.

**Comment by jberkus** [comment]
ah, ok, somehow I thought there were other commands to commctl which weren't covered, but it appears not.  Closing.
